### ISSUE TITLE
Doesn't work with SFC syntax

### ISSUE THREAD

**Issue by JTinkers** [dhershman1/vue-debounce#71] opened 2022-05-15 11:55 UTC
**Describe the bug**
I'm not sure if this is caused by the SFC syntax, but could very well be.

**Version of Vue**
3

**To Reproduce**
1. Setup the plugin
2. Create a dummy input element
3. Set v-debounce with dummy test method
4. Error pops

**Expected behavior**
No error

**Desktop (please complete the following information):**
- Browser: Chrome

**Additional context**
```
vue-debounce.min.js?7965:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attrs')
    at eval (vue-debounce.min.js?7965:1:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js?d2dd:155:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?d2dd:164:1)
    at invokeDirectiveHook (runtime-core.esm-bundler.js?d2dd:3744:1)
    at Array.eval (runtime-core.esm-bundler.js?d2dd:4653:1)
    at flushPostFlushCbs (runtime-core.esm-bundler.js?d2dd:356:1)
    at flushJobs (runtime-core.esm-bundler.js?d2dd:401:1)
```

**Comment by it-xtech-dev** [comment] 2022-05-16 20:51
Same error here (using SFC) here template fragment:
```
              <div>
                <input
                  v-debounce:500ms="() => handleHeaderFilterInput(filter)"
                  v-model.trim="filter.text"
                />
              </div>
```

directive declared as in docs example (component level):
```
  directives: {
    // Pass in 3 to tell the function you're using vue 3, I'm going to work on improving this in the future
    debounce: getDirective("3"),
  }, 
```

**Comment by dhershman1** [comment] 2022-05-16 21:09
I know what the issue is then, I didn't realize that the `attrs` key just didn't exist if there were no attributes on the tag.

and since `v-model` is a directive that wouldn't be read as an attribute. Thanks for the info I know how to fix it!

**Comment by dhershman1** [comment] 2022-05-16 21:30
3.1.1 has been released to npm. If the issues persist please reopen this ticket.

**Comment by it-xtech-dev** [comment] 2022-05-16 21:41
Wow, you're FAST :)

I'm cheking...

**Comment by it-xtech-dev** [comment] 2022-05-16 22:01
Unfortunately same error on my side:

`Cannot read properties of undefined (reading 'attrs')`

package seems to be upgrated:
```
  "dependencies": {
    "vue": "^3.2.33",
    "vue-debounce": "^3.1.1"
  },
```

**Comment by dhershman1** [comment] 2022-05-16 22:10
Did you rebuild the app?

**Comment by it-xtech-dev** [comment] 2022-05-16 22:12
Yup. I have restarted vite.js.

**Comment by dhershman1** [comment] 2022-05-16 22:14
Hmm, that's interesting... I wonder why... 

Can you show me what the function you want debounce to call looks like?

**Comment by it-xtech-dev** [comment] 2022-05-16 22:18
Code map is not much usable, here is where I think error is thrown:
![image](https://user-images.githubusercontent.com/22835881/168691373-56d91f53-d6ba-455b-b6af-fd7740706c7c.png)

Not sure but in source code is line 86 of directive.js?
![image](https://user-images.githubusercontent.com/22835881/168691524-910e5dd3-94d6-452c-9498-4a87ee6593e8.png)

**Comment by dhershman1** [comment] 2022-05-16 22:21
Yeah that for sure should've been changed when you upgraded to 3.1.1, it checks for `attrs` in that function now.

Try ole reliable and `rm -rf` the node_modules file and remove your package-lock then re install the dependencies.

**Comment by it-xtech-dev** [comment] 2022-05-16 22:23
Yes, Check seems to be implemented by error is thrown earlier:
![image](https://user-images.githubusercontent.com/22835881/168692109-383ae63f-a3d8-4614-b3e4-19adc15eaa21.png)

**Comment by dhershman1** [comment] 2022-05-16 22:25
Yeah, I think something is wrong with either `vnode` or maybe data is missing. 

I can't imagine that Vite wouldn't have vnode since it's just using Vue... Well I'll reopen and at least get that fixed.

**Comment by it-xtech-dev** [comment] 2022-05-16 22:28
Have you checked how it work in vue 3 SFC project on your side?

**Comment by dhershman1** [comment] 2022-05-16 22:34
I have built it against SFC and plug and play vue, but I never tried Vite, like the issues with Vuetify it might be that Vite does something different

Let me play around with their environment on stackblitz to see if I can find out what happens to the vnode and get this fixed properly.

**Comment by dhershman1** [comment] 2022-05-17 14:57
So after digging into it, I understand now that the issue is how vue 3 re wrote the vnode object.

When I added compatibility for vue 3 it was in its earlier alpha/beta stages, so I guess that makes sense. I'll need to rebuild the compatibility around vue 3 and re address it. I'll probably also make a new issue for it.

**Comment by it-xtech-dev** [comment] 2022-05-17 15:01
It's nice to hear that you have found source of the problem. When do you plan to release fixed version?

**Comment by dhershman1** [comment] 2022-05-17 15:25
Closing this in favor of #73

**Closed by dhershman1** 2022-05-17 15:25 UTC
Labels: bug :space_invader:, researching :microscope:
