### ISSUE TITLE
Denounce on textarea updates.

### ISSUE THREAD

**Issue by uwejan** [dhershman1/vue-debounce#43] opened 2020-07-16 14:00 UTC
I wish to use denounce on textarea update event. but seems not working, however it does on enter key which is not the intent.
```
    Vue.use(vueDebounce)
    // Listening to multiple events
    Vue.use(vueDebounce, {
        listenTo: ['update']
    })
```
that is my current use. 
Is there a way to denounce on textarea changes.
Edit.
Basically what am aiming for is to call a func when user is still typing. The closest example i could think of is WhatsApp that denounce 2hile you still typing, and stop on keys up.

**Comment by dhershman1** [comment] 2020-07-17 18:14
It's odd that it doesn't debounce the text area for you. I will have to setup some tests and see what could be causing the issue.

**Comment by dhershman1** [comment] 2020-07-18 17:19
So it seems like having the `listenTo` option set in another test file I made breaks the debounce of the `textarea`. I'm not sure why but I shall look into it.

**Comment by uwejan** [comment] 2020-07-19 09:14
@dhershman1 Hi, i wish to listen for `keyup` or keydown` only. Plus, i manged to get infinite update error at some point not sure if related. and i got the textArea input to be very laggy or slow, also not sure if related.

**Comment by dhershman1** [comment] 2020-07-20 14:12
I think having both keyup and keydown in the `listenTo` will have that happen, you should only use one or the other, and by default vue debounce listens to `keyup` unless you populate the `listenTo` field with something else.

If you put both `keyup` and `keydown` here that might explain the lagginess, and probably the infinite update error.

**Comment by uwejan** [comment] 2020-07-20 19:27
@dhershman1  have you made any changes, should i re-test it on textArea ?

**Comment by dhershman1** [comment] 2020-07-21 15:01
Do you mind sharing your setup or creating a reproduction repo I can take a look at? My primary issue right now is re creating the problems you're running into.

If I had that I could better diagnose and see if there's more I can do!

**Comment by dhershman1** [comment] 2020-12-08 21:22
I'm going to close this issue for now since I can't reproduce the issue. If you happen to generate a repo to send my way let me know and we can re open it.

**Closed by dhershman1** 2020-12-08 21:22 UTC
Labels: question :question:
